{% set name = "pdftext" %}
{% set version = "0.3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pdftext-{{ version }}.tar.gz
  sha256: a095ef84c45d3f4e501f7b7632a48fb057d850034152bc7f28f3f43605780998

build:
  entry_points:
    - pdftext = extract_text:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9
    - poetry-core
    - pip
  run:
    - onnxruntime >=1.19.2,<2.0.0
    - python >=3.9,<3.13,!=3.9.7
    - pypdfium2 >=4.29.0,<5.0.0
    - scikit-learn >=1.4.2,<2.0.0
    - pydantic >=2.7.1,<3.0.0
    - pydantic-settings >=2.2.1,<3.0.0

test:
  imports:
    - pdftext
  commands:
    - pip check
    - pdftext --help
  requires:
    - pip

about:
  home: https://github.com/VikParuchuri/pdftext
  summary: Extract structured text from pdfs quickly
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
